name: Deploy Python Functions to PolyAPI

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: PolyAPI Deployment Action (Python)
      uses: polyapi/poly-deployment-action-py@v0.0.8
      with:
        poly_api_key: ${{ secrets.POLY_API_KEY }}
        poly_api_base_url: ${{ secrets.POLY_API_BASE_URL }}
        do_checkout: false
        working_directory: .
